<?php
$meta_title = "Terms And Conditions - Nitve";
$meta_desc = "“Nitve” is a trademark of Nitve Ecommerce Private Limited (“Company”), a company incorporated under the Companies Act, 2013. The domain name nitve-ecommerce.com is owned by the Company.";
?>
@include('head')
@include('menu')
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="d-block w-100" src="assets/img/Banner2.png" alt="First slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="assets/img/Banner3.png" alt="Second slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="assets/img/Banner4.png" alt="Third slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="assets/img/Banner111.png" alt="Fourth slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="assets/img/Banner555.png" alt="Fifth slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="assets/img/Banner4444.png" alt="Sixth slide">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<section class="pt-5">
    <div class="container">
        <h1 class="section-title">Terms & Conditions</h1>
        <p class="text-justify">“Nitve” is a trademark of Nitve Ecommerce Private Limited (“Company”), a company incorporated under the Companies Act, 2013. The domain name nitve-ecommerce.com is owned by the Company. It is strongly recommended that you read and understand these ‘Terms of Use’ carefully, as by accessing this site (hereinafter the “Marketplace”), you agree to be bound by the same and acknowledge that it constitutes an agreement between you and the Company (hereinafter the “User Agreement”). If you do not agree with this User Agreement, you should not use or access the Marketplace for any purpose whatsoever. This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures. This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of App / Website.</p>
    </div>
</section>
<section class="pt-5">
    <div class="container">
        <h1 class="section-title sub-title">Services Overview</h1>
        <p class="text-justify">The Marketplace is a platform for domestic consumers to transact with third party sellers, who have been granted access to the Marketplace to display and offer products for sale through the Marketplace. For abundant clarity, the Company does not provide any services to users other than providing the Marketplace as a platform to transact at their own cost and risk, and other services as may be specifically be notified in writing. The Company is not and cannot be a party to any transaction between you and the third party sellers, or have any control, involvement or influence over the products purchased by you from such third party sellers or the prices of such products charged by such third-party sellers. The Company therefore disclaims all warranties and liabilities associated with any products offered on the Marketplace. Services on the Marketplace are available to only select geographies in India and are subject to restrictions based on business hours and days of third-party sellers. Transactions through the Marketplace may be subject to a delivery charge where the minimum order size is not met. You will be informed of such delivery charges at the stage of check-out for a transaction through the Marketplace.</p>
    </div>
</section>
<section class="pt-5">
    <div class="container">
        <h1 class="section-title sub-title">Eligibility</h1>
        <p class="text-justify">Persons who are “incompetent to contract” within the meaning of the Indian Contract Act, 1872 including minors, un-discharged insolvents etc. are not eligible to use/access the Marketplace. However, if you are a minor, i.e. under the age of 18 years, you may use/access the Marketplace under the supervision of an adult parent or legal guardian who agrees to be bound by these Terms of Use. You are however prohibited (even under provision) from purchasing any product(s) which is for adult consumption, the sale of which to minors is prohibited. The Marketplace is intended to be a platform for end-consumers desirous of purchasing product(s) for domestic self-consumption. If you are a retailer, institution, wholesaler or any other business user, you are not eligible to use the Marketplace to purchase products from third-party sellers, who have been granted access to the Marketplace to display and offer their products for sale through the Marketplace. The Company, in its sole discretion and without liability, reserves the right to terminate or refuse your registration, or refuse to permit use/access to the Marketplace, if: (i) it is discovered or brought to notice that you do not conform to the eligibility criteria, or (ii) the Company has reason to believe (including through evaluating usage patterns) that the eligibility criteria is not met/is violated by a user, or (iii) may breach the terms of this User Agreement. In order to determine compliance with eligibility criteria, the Company inter alia uses an algorithm and/or pre-determined criteria based technology and accordingly, from time to time, your usage may be restricted or blocked on account of overlap with such algorithms/predetermined criteria. In such cases, if you are a genuine domestic user of the Platform, please contact us for assistance.</p>
    </div>
</section>
<section class="pt-5">
    <div class="container">
        <h1 class="section-title sub-title">License & Access</h1>
        <p class="text-justify">The Company grants you a limited sub-license to access and make personal use of the Marketplace, but not to download (other than page caching) or modify it, or any portion of it, except with express prior written consent of the Company. Such limited sublicense does not include/permit any resale or commercial use of the Marketplace or its contents; any collection and use of any product listings, descriptions, or prices; any derivative use of the Marketplace or its contents; any downloading or copying of information for the benefit of another third party; or any use of data mining, robots, or similar data gathering and extraction tools. The Marketplace or any portion of the Marketplace may not be reproduced, duplicated, copied, sold, resold, visited, or otherwise exploited for any commercial purpose without express prior written consent of the Company. You may not frame or utilize framing techniques to enclose any trademark, logo, or other proprietary information (including images, text, page layout, or form) of the Marketplace or of the Company and/or its affiliates without the express prior written consent of the Company. You may not use any meta tags or any other “hidden text” utilizing the Company’s name or trademarks without the express prior written consent of the Company. You shall not attempt to gain unauthorized access to any portion or feature of the Marketplace, or any other systems or networks connected to the Marketplace or to any server, computer, network, or to any of the services offered on or through the Marketplace, by hacking, ‘password mining’ or any other illegitimate means. You hereby agree and undertake not to host, display, upload, modify, publish, transmit, update or share any information belongs to another person and to which you do not have any right; is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, paedophilic, libelous, invasive of another’s privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever; harms minors in any way; infringes any patent, trademark, copyright or another proprietary/intellectual property rights; violates any law for the time being in force; deceives or misleads the addressee about the origin of such messages communicates any information which is grossly offensive or menacing in nature; impersonates another person; contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource; threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offense or prevents investigation of any offense or is insulting any other nation; is misleading or known to be false in any way. Any unauthorized use shall automatically terminate the permission or sub-license granted by the Company.</p>
    </div>
</section>
<section class="pt-5">
    <div class="container">
        <h1 class="section-title sub-title">Account & Registration Obligations</h1>
        <p class="text-justify">All users must register and log in for placing orders on the Marketplace. You must keep your account and registration details current and correct for all communications related to your purchases from the Marketplace. By agreeing to the Terms of Use, the user agrees to receive promotional or transactional communication and newsletters from the Company and its partners. The user can opt out from such communication and/or newsletters either by or by contacting the customer services team of Marketplace and placing a request for the same.</p>
    </div>
</section>
<section class="pt-5">
    <div class="container">
        <h1 class="section-title sub-title">Pricing</h1>
        <p class="text-justify">The Company aims to ensure that prices of all products offered for sale are true and correct. However, from time to time, the prices of certain products may not be current or may be inaccurate on account of technical issues, typographical errors or incorrect product information provided to the Company by third-party sellers. In each such case, notwithstanding anything to the contrary, the Company reserves the right to cancel the order without any further liability. Subject to the foregoing, the price mentioned at the time of ordering a product shall be the price charged at the time of delivery, provided that no product offered for sale on the Marketplace will be sold at a price higher than its MRP (Maximum Retail Price).</p>
    </div>
</section>
<section class="pt-5">
    <div class="container">
        <h1 class="section-title sub-title">Order Limit & Minimum Order Value</h1>
        <p class="text-justify">There is no minimum order value to place an order with Nitve. Every store has its own delivery charges, which are waived off if you order above a specified minimum amount from the store. The minimum charges and the delivery charges are mentioned on the app at the checkout page.</p>
    </div>
</section>
<section class="pt-5">
    <div class="container">
        <h1 class="section-title sub-title">Coupons & Promo Codes</h1>
        <p class="text-justify">*Please note: From time to time, the Company may, at its discretion, offer a user promotional codes or coupons entitling you to encash the applicable value of such codes/coupons against purchases made on the Marketplace. Unless specifically stated on the code or coupon, a promotional code or coupon shall: Expire at 12:00 AM (inclusive of the issuance date) from the date of issuance endorsed thereon.</p>
    </div>
</section>
<section class="pt-5">
    <div class="container">
        <h1 class="section-title sub-title">Cancellations</h1>
        <p class="text-justify">As a user, you may cancel an order placed by you before the order enters the “dispatched” stage. For any permitted cancellations, we will refund payments, if any, made by you under the relevant order within approximately 48-72 hours. Orders may be cancelled by the Company in any of the following cases: (a) if it is suspected that a customer has undertaken a fraudulent transaction, or (b) if it is suspected that a customer has undertaken a transaction which does not conform to or violates these Terms of Use/User Agreement, or (c) in case of unavailability of product(s), or (d) for any reason outside the control of the Company including causes for delivery related logistical difficulties. For such cancellations, the Company will refund the payment, if any, made by you under the relevant order within 72 hours. Further, while precautions are taken to ensure accuracy of product specifications, the details of a product as reflected on the Marketplace may be inaccurate due to technical issues, typographical errors or incorrect product information provided to the Company by third party seller and in such an event you shall be notified as soon as such error comes to the notice of the Company. In such an event, the Company reserves the right to cancel your order and grant credit/coupon for the value of the returned product. Such credit shall be available for use against a subsequent invoice for transactions on the Marketplace. We maintain a list of all fraudulent transactions and non-complying users, and reserve the right to deny access to such users at any time or cancel any orders placed by them in future.</p>
    </div>
</section>
<section class="pt-5">
    <div class="container">
        <h1 class="section-title sub-title">Returns & Refunds</h1>
        <p class="text-justify">To combat the Corona pandemic, we’re minimizing contact points, and hence, will not be able to process returns if not done at doorstep, each return request will be reviewed and actioned considering current situation, all below benefits of return policy are void till 31st March’20. The Marketplace has a “no questions asked return and refund policy” which entitles all users who have purchased a product on the Marketplace to return the product at the time of delivery if they are not satisfied with the quality of the product.</p>
    </div>
</section>
<section class="pt-5">
    <div class="container">
        <h1 class="section-title sub-title">Return Policy</h1>
        <p class="text-justify">If you want to return a product, please keep the product in the original packaging. In addition, the product must be unused and unwashed, with all tags intact. Non-returnable products information visible in the product info/description section on the website/app: A few products may not be eligible for return and will be marked “Non-returnable” on the product details page. In case you are not available at delivery to check the quality of the product(s), you may raise a complaint within 24-48 hours of delivery. Similarly, in case any product is not delivered at the time of delivery, you may raise a complaint within 48 hours of delivery. To pass feedback to the merchants to improve the services, it is mandatory to share the images of the items which you were dissatisfied with. Subject to acceptance from the third-party seller of the product, the Company may take the returned product back and grant credit/coupon in lieu of the value of the returned product. Such credit shall be available for use against a subsequent invoice for transactions on the Marketplace. You may request for a refund/replacement within 7 days of delivery, it is also requested that a user should check if the product seal is intact (i.e. not broken) while accepting the order to avoid any kind of damage related complaints post-delivery. Please note: Few items listed may or may not carry a seller warranty to which Nitve will support basis return policy. Refund, if any, shall be made at the same issuing bank through which the Product was purchased. For cash on delivery transactions, the User has the option to receive in any bank account via NEFT (for which the User shall have to share the bank details). For payments made through electronic means like debit card, credit card, net banking, wallet etc. refund shall be made using the same payment mode. All refunds shall be made in Indian Rupees only.</p>
    </div>
</section>
<section class="pt-5">
    <div class="container">
        <h1 class="section-title sub-title">You Agree & Confirm</h1>
        <p class="text-justify">That in the event any product delivery is delayed or is returned from its destination on account of a mistake by you (e.g. providing the wrong name or address or other incorrect/misleading information), any additional costs incurred by the Company for re-delivery of the product(s) shall be borne by you We will not be held responsible for any delay or failure to make delivery of your order if the delay or failure arises from any cause which is beyond our reasonable control. You agree to use the services provided by the Company for lawful purposes only and comply with all applicable laws and regulations while using/accessing and transacting on the Marketplace. You will provide authentic and true information in all instances where any information is requested of you. The Company reserves the right to confirm and validate the information and other details provided by you at any point of time. If at any time, the information provided by you is found to be false or inaccurate (wholly or partly), the Company shall have the right in its sole discretion to reject registration, cancel all orders, and debar you from using its services and other affiliated services in the future without any prior intimation whatsoever, and without any liability to you. You are accessing the services made available by the Company and transacting at your sole risk and are using your best and prudent judgement before entering any transaction through the Marketplace. Before placing an order, you acknowledged to have checked and reviewed the product description carefully and in enough detail. By placing an order on the Marketplace, you agree to be bound by the conditions of sale included in the item’s description without exception. Notwithstanding the right of the Company on cancellation of the order, any Product in the order may be replaced by the Company in case of unavailability or for other reasons outside the control of the Company, subject to you may refuse to accept such replacement/substitute product. For such cancellations, the Company will refund the payment of the order/product, if any, made by you under the relevant order within 72 hours.</p>
    </div>
</section>
<section class="pt-5">
    <div class="container">
        <h1 class="section-title sub-title">Disclaimers</h1>
        <p class="text-justify">You acknowledge and undertake that you are accessing the services on the website and transacting at your own risk and are using your best and prudent judgement before entering into any transactions. The Company make best efforts to display available products, including in respect of their colour, size, shape and appearance, as accurately as possible. However, the actual colour, size, shape and appearance may have variations from the depiction on your mobile/computer screen. The Company does not make any representation or warranties in respect of the products available on the Marketplace nor does the Company implicitly or explicitly support or endorse the sale or purchase of any products on the Marketplace. The Company accepts no liability for any error, inaccuracy or omission of third parties or for information/inputs received from third parties and provided to you through the Marketplace or otherwise. You acknowledge and agree that the Company shall not, at any time, have any right, title or interest to any product(s), which is subject to a bipartite sale and purchase contract between you and the relevant third party seller. The Company does not have any control over the quality, failure to provide or any other aspect whatsoever of the product(s) and is not responsible for damages or delays on account of products which are out of stock, unavailable or back ordered.</p>
    </div>
</section>
<section class="pt-5">
    <div class="container">
        <h1 class="section-title sub-title">Reviews, Feedback, Submissions</h1>
        <p class="text-justify">All reviews, comments, feedback, suggestions, ideas, and other submissions disclosed, submitted or offered on the Marketplace or otherwise disclosed, submitted or offered in connection with use of the Marketplace (collectively, the Comments) shall be and remain the property of the Company. Such disclosure, submission or offer of any Comments shall constitute an assignment to the Company of all worldwide rights, titles and interests in all copyrights and other intellectual properties in the Comments. Thus, the Company shall exclusively own all such rights, titles and interests in the Comments and shall not be limited in any way in its use, commercial or otherwise. The Company will be entitled to use, reproduce, disclose, modify, adapt, create derivative works from any Comments, and publish, display and distribute any Comments submitted for any purpose whatsoever without restriction and without compensating the user in any way. The Company is and shall be under no obligation to: (i) maintain any Comments in confidence; or (ii) pay compensation for any Comments; or (iii) respond to any Comments. You agree that any Comments submitted by you on the Marketplace will not violate the Terms of Use or any right of any third party, including copyright, trademark, privacy or other personal or proprietary right(s), and will not cause injury to any person or entity. You further agree that no Comments submitted by you on the Marketplace will be or contain libelous or otherwise unlawful, threatening, abusive or obscene material, or contain software viruses, political campaigning, commercial solicitation, chain letters, mass mails or any form of ‘spam’. The Company does reserve the right (but assumes no obligation) to monitor, edit and/or remove any Comments submitted on the Marketplace. You hereby grant the Company the right to use names that you submit in connection with any Comments. You agree not to use a false email address, impersonate any person or entity, or otherwise mislead as to the origin of any Comments you submit. You are, and shall remain, responsible for the content of any Comments you make and you agree to indemnify the Company and its affiliates against all claims, loss and liabilities resulting from any Comments you submit. Further, any reliance placed on Comments available on the Marketplace from a third party shall be at your sole risk and expense.</p>
    </div>
</section>
<section class="pt-5">
    <div class="container">
        <h1 class="section-title sub-title">Copyright & Trademark</h1>
        <p class="text-justify">The Company, its suppliers and licensors expressly reserve all intellectual property rights in all text, programs, products, processes, technology, images, content and other materials which appear on the Marketplace. Access to or use of the Marketplace does not confer and should not be considered as conferring upon anyone any license, sub-license to the Company’s intellectual property rights. All rights, including copyright, in and to the Marketplace are owned by or licensed to the Company. Any use of the Marketplace or its contents, including copying or storing it or them in whole or part is prohibited without the express prior written consent of the Company. You may not modify, distribute or re-post anything on the Marketplace for any purpose. The names and logos and all related product and service names, design marks and slogans are the trademarks/service marks of the Company, its affiliates, its partners or its suppliers/service providers. All other marks are the property of their respective owners. No trademark or service mark license is granted in connection with the materials contained on the Marketplace. Access to or use of the Marketplace does not authorize anyone to use any name, logo or mark in any manner. References on the Marketplace to any names, marks, products or services of third parties or hypertext links to third party sites or information are provided solely as a convenience to you after having express consent from third parties and do not in any way constitute or imply the Company’s endorsement, sponsorship or recommendation of the third party, the information, its product or services. The Company is not responsible for the content of any third-party sites and does not make any representations regarding the content or accuracy of material on such sites. If you decide to access a link of any third-party websites, you do so entirely at your own risk and expense.</p>
    </div>
</section>
<section class="pt-5">
    <div class="container">
        <h1 class="section-title sub-title">Wholesale Trading Terms</h1>
        <p class="text-justify">You acknowledge and agree that the terms and conditions set out on the Marketplace (including as contained herein – (Conditions-of-Supply and Wholesale Trade) are the terms and conditions applicable to any order placed by you on the App, unless a separate written instrument is executed in relation to a specified order to prevail over these Conditions of Contract.</p>
    </div>
</section>
<section class="pt-5">
    <div class="container">
        <h1 class="section-title sub-title">Objectionable Material</h1>
        <p class="text-justify">You understand that by using the Marketplace or any services provided on the Marketplace, you may encounter content that may be deemed by some to be offensive, indecent, or objectionable, which content may or may not be identified as such. You agree to use the Marketplace and any service at your sole risk and that to the fullest extent permitted under applicable law, the Company and its affiliates shall have no liability to you for any content that may be deemed offensive, indecent, or objectionable to you.</p>
    </div>
</section>
<section class="pt-5">
    <div class="container">
        <h1 class="section-title sub-title">Indemnity</h1>
        <p class="text-justify">You agree to defend, indemnify and hold harmless the Company, its employees, directors, officers, agents and their successors and assigns from and against any and all claims, liabilities, damages, losses, costs and expenses, including attorney’s fees, caused by or arising out of claims based upon a breach of any warranty, representation or undertaking in this User Agreement, or arising out of a violation of any applicable law (including but not limited in relation to intellectual property rights, payment of statutory dues and taxes, claims of libel, defamation, violation of rights of privacy or publicity, loss of service by other subscribers and infringement of intellectual property or other rights). This clause shall survive the expiry or termination of this User Agreement.</p>
    </div>
</section>
@include( "footer")
